### ISSUE TITLE
FORCE_SSL_ADMIN in wp-config.php is not working

### ISSUE THREAD

**Issue by qa-majeed** [khaleel-git/ngnix-reverse-proxy-wordpress-setup#4]
adding this in wp-config.php is not working: define('FORCE_SSL_ADMIN', true);
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
    $_SERVER['HTTPS'] = 'on';
}

**Comment by khaleel-git** [comment]
try adding this line only: $_SERVER['HTTPS'] = 'on';

**Comment by khaleel-git** [comment]
Comment these blocks: 
```
define('FORCE_SSL_ADMIN', true);
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
    $_SERVER['HTTPS'] = 'on';
}
```
and 
```
define('WP_HOME', 'http://example.com');
define('WP_SITEURL', 'http://example.com');
```
